spring:
  profiles:
    group:
      test: test
      prod: prod
---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:/org/springframework/batch/core/schema-drop-h2.sql
        - classpath:/org/springframework/batch/core/schema-h2.sql
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devly-local;MODE=MySQL
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core: TRACE
openai:
  api-url: https://api.openai.com
  api-key: d

server:
  port: 8090
---
spring:
  config:
    activate:
      on-profile: prod
  batch:
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/devly?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    hibernate:
      ddl-auto: none
---
