spring:
  profiles:
    group:
      test: test
      prod: prod
---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devly-local;MODE=MySQL
    username: user
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
front:
  url: http://localhost:3000
jwt:
  secret-key:
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.core: TRACE
---
spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: profile, email
            redirect-uri: https://devly.kro.kr/login/oauth2/code/google
front:
  url: http://localhost:3000
jwt:
  secret-key:
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800

