= RESTful API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== 단어
=== 단어 목록 조회
operation::word-list[snippets='http-request']
operation::word-list[snippets='http-response']

== 학습
=== 학습 상태 조회
operation::study-tasks[snippets='http-request']
operation::study-tasks[snippets='http-response']

=== [단어] 학습 결과 생성
operation::create-word-review[snippets='http-request']
operation::create-word-review[snippets='http-response']
=== [단어] 학습 결과 업데이트
operation::update-word-review[snippets='http-request']
operation::update-word-review[snippets='http-response']
=== [단어] 학습 결과 조회
operation::get-word-reviews[snippets='http-request']
operation::get-word-reviews[snippets='http-response']

=== [PR] PR 조회
operation::pr-info[snippets='http-request']
operation::pr-info[snippets='http-response']
=== [PR] 변경 파일 조회
operation::pr-changed-files[snippets='http-request']
operation::pr-changed-files[snippets='http-response']
=== [PR] 질문 내역 조회
operation::pr-comments[snippets='http-request']
operation::pr-comments[snippets='http-response']
=== [PR] 커멘트 리뷰 요청
operation::pr-comment-review[snippets='http-request']
operation::pr-comment-review[snippets='http-response']

